### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by alexmaragko** [PAHFIT/pahfit#109]
Pahfit fails to install on a remote machine with the `pip install -e .` command, giving the following error message when run from a conda environment, and pip version 20.3.3:

ERROR: Command errored out with exit status 1:
   command: /home/alexm/anaconda3/envs/astroconda/bin/python /home/alexm/anaconda3/envs/astroconda/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-dman4_j0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel
       cwd: None
  Complete output (8 lines):
  Collecting setuptools_scm
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1076)'))': /packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1076)'))': /packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1076)'))': /packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1076)'))': /packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1076)'))': /packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl
  ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1076)')))
  
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/alexm/anaconda3/envs/astroconda/bin/python /home/alexm/anaconda3/envs/astroconda/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-dman4_j0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel Check the logs for full command output.

**Comment by alexmaragko** [comment]
I was able to install pahfit with the following command found in various similar raised issues on the pip repo:

`pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org git+https://github.com/PAHFIT/pahfit.git`

**Comment by karllark** [comment]
So, this does not sound like a pahfit error.  But something to do with how the remote computer is setup?  Can you confirm?  Is this something we need to add to the pahfit docs, maybe with just a pointer?  Or is this something separate?  I've never run into this problem before, hence all my questions.

**Comment by alexmaragko** [comment]
Yes eventually this is not related to pahfit as other packages are facing the same issue. So most probably this has to do with the remote computer setup. I guess we could add this to the docs as an alternative installation command? First time I run into this myself.

**Comment by karllark** [comment]
I would be ok with a note about this and pointer to details somewhere else would be reasonable.  A small docs PR.

**Comment by alexmaragko** [comment]
Sounds good.
