### ISSUE TITLE
Continuum fitting

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#11]
Incorporate alternative dust continuum fitting.

**Comment by els1** [comment]
The current set of parameters have trouble to fit the continuum when it rises very strongly in the 10-15um region. Also it sometimes uses the dust feature at ~33um to compensate for the lack of continuum at the longer wavelengths.

**Comment by hwwspoon** [comment]
Do you have an example, @els1 ?

**Comment by jdtsmith** [comment]
I often turn off 33µm dust for that reason.  That was a predicted graphite band that never materialized.  Are you sure these types of issues aren't caused by attenuation/extinction?  In my experience (of mostly galaxy spectra) that's almost always what makes PAHFIT miss the continuum level badly.

**Comment by jdtsmith** [comment]
Let's continue in #299.
