### ISSUE TITLE
The argument "estimate_start" overwrites the values for parameters fixed in the pack file 

### ISSUE THREAD

**Issue by Ameek-Sidhu** [PAHFIT/pahfit#110]
While comparing the results for PAHFIT IDL with the python version using the spectra of NGC 2023, I modified the following parameters in the sci pack file:
Set the amplitudes of H2 S(7), H2 S(6), and H2 S(4) to zero and fixed their amplitudes.

However, when I run the script (run_pahfit) using the argument 'estimate_start', the amplitudes for these features which should be zero in this case are overwritten by the values guessed by the estimate function. 

![Input_file](https://user-images.githubusercontent.com/52894803/112072012-53cfd380-8b47-11eb-8b4a-999615c5d408.png)
![Output_file](https://user-images.githubusercontent.com/52894803/112072034-5b8f7800-8b47-11eb-87d0-39452a8703a2.png)

**Comment by Ameek-Sidhu** [comment]
When I run the same script (run_pahfit) without the argument 'estimate_start', the amplitudes for the features remain fixed at zero.
![output_without_estimate_argument](https://user-images.githubusercontent.com/52894803/112072452-3bac8400-8b48-11eb-85e7-83316e71e6f1.png)

**Comment by alexmaragko** [comment]
https://github.com/PAHFIT/pahfit/blob/13f4169d8704389807aedb80559533f9643aeba0/pahfit/base.py#L625-L647

Shouldn't all the `param_info[x]['amps'][i] = amp_guess` lines be indented to match the amp_guess above?

**Comment by els1** [comment]
I don't think so. If the amplitude is fixed in the input file, it should not be overwritten by the estimator.

**Comment by alexmaragko** [comment]
I was talking about the indentation of the param_info line(s) that they should probably match the indentation of the amp_guess line(s). Are you referring to the same thing @els1 ?

**Comment by els1** [comment]
Sorry. Too early in the morning.

**Comment by els1** [comment]
I thought the same about the indentation. You only want to set the amplitude to that of the estimator when the amplitude is not fixed in the input file.

**Comment by karllark** [comment]
Sounds like a small PR would fix this issue.  @alexmaragko : is this your plan?

**Comment by alexmaragko** [comment]
Absolutely, if you agree to the above.

**Comment by karllark** [comment]
I do!

**Comment by karllark** [comment]
Fixed in PR #111.
