### ISSUE TITLE
Issue with run_pahfit when S07_att's amp = 0.0 and amp_fixed = True

### ISSUE THREAD

**Issue by BethanyRS** [PAHFIT/pahfit#112]
Setting amp = 0.0 and amp_fixed = True for S07_att (the last row in scipack_ExGal_SpitzerIRSSLLL.ipac) results in the output

"The cosine of the angle between func(x) and any column of the
  Jacobian is at most 0.000000 in absolute value"

**Comment by Minnielam** [comment]
@BethanyRS @karllark I got the same issue when I used run_pahfit. How can I solve it? Thanks a lot.

**Comment by karllark** [comment]
Simple fix.  PR opened (see above).  Should be merged soon.
