### ISSUE TITLE
run_pahfit and plot_pahfit entrty point error on Windows OS

### ISSUE THREAD

**Issue by DanialKhan6312** [PAHFIT/pahfit#118]
Running the commands from the documentation "run_pahfit M101_Nucleus_irs.ipac scipack_ExGal_SpitzerIRSSLLL.ipac" on Windows system results in the error " ModuleNotFoundError: No module named 'pahfit.scripts' ".

**Comment by karllark** [comment]
Can you try adding an empty `__init__.py` file in the pahfit/scripts directory?  This is needed to identify the scripts directory as a module.  Maybe this will fix the issue.

**Comment by DanialKhan6312** [comment]
Didn't seem to have an effect when adding the __init__.py but it may be a result of the `tox -e build docs` command which gives this output after finishing 
"dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting"
