### ISSUE TITLE
Inclusion of Drude1D and Gaussian1D in doc?

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#122]
Do we need to include Drude1D and Gaussian1D alongside BlackBody1D and S07_attenuation in the documentation? 

https://pahfit.readthedocs.io/en/latest/index.html#module-pahfit.component_models

**Comment by karllark** [comment]
We could/should move to using the astropy versions of these models.  Both are there now, so that would remove the need for us to support them.  Maybe the Gauss1D has already moved?

**Comment by els1** [comment]
Correct. Although perhaps a link to it would be good for completeness and reference? 
Gaussian1D comes from astropy.modeling.functional_models and Drude1D from astropy.modeling.physical_models.

**Comment by karllark** [comment]
Maybe just state that we use the astropy versions.  Probably not important to say exactly where given this level of detail is clearly given in the code.
