### ISSUE TITLE
Implement structured save/read report files

### ISSUE THREAD

**Issue by alexmaragko** [PAHFIT/pahfit#13]
Save modeling and fitting parameters of all feature components, as well as read/load them back into the main code.

**Comment by jdtsmith** [comment]
Excellent idea.  If we do decide to go the MCMC/Bayesian route, we'd need to save room in this structure for posterior probabilities of parameters, not just straight 1-sigma uncertainty.

**Comment by karllark** [comment]
One idea.  Can we make the report file the same format as the science pack?  Would be really cool if one could use the results from a fit as input for another fit.

**Comment by jdtsmith** [comment]
That's an interesting thought.  You mean to initialize parameters?  It reminds me to start an issue about that...

**Comment by karllark** [comment]
That was my thought.

**Comment by jdtsmith** [comment]
OK, I opened issue #31 to discuss parameter init generally.  But I really like the idea of being able to give PAHFIT the results of an old fit and say ("start with this").  Right now you can do that but it's a bit of a pain to translate between output structure and input parameter info.  Parameter info has way more to it, however (bounds, constraints, parameter ties, etc.).

**Comment by karllark** [comment]
Yes, there is more info.  But maybe that would be good to have in the output report to better understand the model results.  So, good to have for input *and* output.

**Comment by alexmaragko** [comment]
I've started working on the save and read functions on pahfit and it's probably a good time to discuss and decide on the file format we are going to use.

One flexible option would be HDF5 format (the Python interface is the h5py package: https://www.h5py.org), especially since we are thinking of adding many diverse parameters in the future (like MCMC results).

Additionally we could perhaps output an ascii file similar to the output format of the standard IDL pahfit if necessary.

Let me know what you think.

**Comment by karllark** [comment]
One could even look to the future and think about ASDF.

https://asdf-standard.readthedocs.io/en/stable/

https://github.com/spacetelescope/asdf

**Comment by jdtsmith** [comment]
For the input packs I think human readable is the way to go.  Probably YAML is most Python-y, but I'm happy to take suggestions (I'd probably opt for JSON otherwise).  For fitter output, that's a different issue.  It's very common for IDL PAHFIT people to store an IDL SAV file (which is internally HDF5 with some extensions), in particular when you are PAHFIT'ing a huge number of spectra (e.g. in a spectral cube) and want to store them all.  It's not a huge amount of data, but when working with thousands of fits, which need to be manipulated and queried, it adds up.  ASDF sounds pretty cool.  Any signs that it will take off (many "next generation file storage formats" have come and gone)?

**Comment by jdtsmith** [comment]
A related concern is what format we'll accept for input _spectra_ to be fit.  Is there a canonical package that does this for us, and we can just hook into its format input capabilities?

**Comment by karllark** [comment]
We should look at specutils for the input format of the spectra.  If we can hook into what they are doing, then we should gain in not having to maintain/setup our own format.

https://github.com/astropy/specutils

**Comment by karllark** [comment]
As for ASDF, I think it will survive.  JWST will be using it by necessity for IFU data (FITS cannot handle all that is needed).  If we focus on using astropy tables as our interface for the pahfit inputs/results, we can even be robust to the on disk format.  Maybe possible to provide a generic interface to properly formatted ascii, FITS, ASDF, hdf5 files as the standard Table.read() function figures out the format and puts everything in a Table object.

**Comment by jdtsmith** [comment]
Sounds like a good plan.  I guess the Table object can write in whatever format as well.   Could default to ASDF but allow the user to pick.  The guiding principle should be "what if I find a pile of PAHFIT output from 20 years ago, am I able to read it?"  From my brief perusal, specutils doesn't cover disk format input/output, but leaves that to the user.  I do like their units capabilities (PAHFIT has always assumed at a deep level an f_nu unit scheme, but in principle specutils could help open that up to f_lambda flavors as well).

**Comment by alexmaragko** [comment]
If everyone agrees we should use ASDF, I can invest time on that. 
Otherwise I could start with either a multi-extension FITS file or astropy table to get things going, since the current example input spectra we are using are single spectra and not a cube.

**Comment by jdtsmith** [comment]
Looking into ASDF sounds good. But we need to carefully separate two (disk) format issues: i) input spectral type, and ii) output PAHFIT results.  

For input spectra, people will have whatever crazy on-disk spectrum format they have, and we should endeavor to make it easy for them to get those into PAHFIT (e.g. using Karl's Table.read() idea).  We can really only control or influence _output_ format.  This is where ASDF (or others, by user choose) could come in.   We should plan from the start to have the flexibility to accommodate many PAHFIT results in the output (think spectral cube).   In IDL-land, you'd make an array of PAHFIT structures and save that in an IDL .sav file, for example.

**Comment by alexmaragko** [comment]
Yes I totally agree it is important to decide on the input format as well.

Currently I'm focusing on working on the output as well as on the function that reads this output back as let's say input for another fit or examination of results etc.

So let me know if there is a preference on the output file format (even if it is temporary) to get started.

**Comment by karllark** [comment]
@alexmaragko : any progress?  No great preference on the output format from my side.  Something that is table like would be best - as long as astropy.tables can read it, then we should be able to change the format later w/ minimal (or no) updates.  Might be good to start with formatted ascii tables as these are human readable.

**Comment by alexmaragko** [comment]
I was waiting input from you and J.D. to decide on the output format as different options were put on the table (HDF5, ASDF, FITS, and astropy data tables). I would't want to spend time on a given format and then we might decide to change it later. Although changing directions is quite common at least at the initial steps of such projects, I will begin with astropy table formats as of today.

**Comment by karllark** [comment]
Apologies for not responding sooner.  
I would suggest starting with the output code.  You could set it up as an astropy Table and then the output format can be picked when the file is written.  My thought is that if it can be written with Table.write(), then it should be able to be read by Table.read().  And Table and read/write lots of different formats - FITS, various flavors of ascii, hdf5, asdf, ....  We should take advantage of all the work on astropy tables by others!  :-)

**Comment by alexmaragko** [comment]
No worries. Looking into it. :)

**Comment by karllark** [comment]
Great!

**Comment by karllark** [comment]
We now have a save format.   It should be be easily readable as input, including defining simple constraints, specifically fixed and bounded parameters.  But need the input code to be written to be sure.

**Comment by alexmaragko** [comment]
That's the next thing I'll work on. I'm wondering if this is going to be something standalone or be part of PAHFIT.py, and if it's the latter in what sequence should we call the "read" function.
For example, if the read function is called first, then do we bypass the fitting process and simply load all components e.g., for re-plotting? Or should we also give the option to re-fit ?

**Comment by karllark** [comment]
For this issue, the reading would be to set the initial guess at the parameters, the bounds and which ones are fixed.  The idea would be to allow the option to use a the file to give all the parameter info instead of hard coding them in SciPackExGal class.  One idea would be to keep the hard-coded defaults, but allow using the file inputs instead.  The reading function should be a member function of PAHFITBase (i.e., flesh out the 'read' function).

Given your comment about replotting, I think we should have a separate script (e.g., plot_pahfit.py?) that would plot the saved results of the fit with the observed spectrum.  Should be a fairly straightforward script to write I think.  Should use the reading in function that is needed in general (previous paragraph) and the plotting function already written.  All member functions of PAHFITBase.  Makes things "easy" I hope, at least that is the general plan in my brain.

**Comment by jdtsmith** [comment]
I don't think we should have ANY hard-coded parameters, but instead have a default set of model pack files that we distribute, and a default one that is loaded if nothing else is chosen.  I am working on a `YAML` file input format that will be usable for both model and calibration packs.  So we're actually talking about 4 things in this thread:

1. Input spectrum formats, including units, uncertainty, flux vs. surface brightness flavors, etc.
2. Model pack inputs, which specify all the parameters, constraints and ties on those parameters.
3. Calibration pack inputs, which specify instrument-specific constraints like line spread function (aka resolution), any flux offsets we want to include.
4. Fitting result outputs (aka the `PAHFIT` structure in IDL parlance), which captures all the resultant parameter fits, as well as derived quantities from those fits (integrated strength, combined feature strength, equivalent width, etc., etc.). Some capacity for multiple such structure in an array configuration (for fitting an IFU worth of spectra, for example), might be important to.  

I started a [wiki page](https://github.com/PAHFIT/pahfit/wiki/File-Formats) to begin drafting how this will look.  Perhaps easier to collect documentation on the various formats there.  I think Karl has proposed having file format 4 be interoperable with file format 2 and 3, which is a reasonable thought, though `PAHFIT` doesn't update any constraints/etc. as a result of the fitting... But perhaps this point needs more discussion.

**Comment by karllark** [comment]
Having the format of 4 be compatible with 2 & 3 would serve two purposes.  The constraints used for the fit would be logged with the best fit, etc. info.  This could be very useful in the future to know how the fit results were obtained.  Second, the best fit, etc. can be used as a starting point for a new fit - could be quite helpful when fitting IFU cubes where neighboring spaxels will likely have similar fits.

**Comment by karllark** [comment]
Being flexible about the format of the input/output files would be good.  This is why I advocated using astropy.tables internally for the output in @alexmaragko work on the output file.  This would allow us to input/output in ascii tables, FITS files, etc. without having to write the parsing code ourselves.  There are a number of supported formats (http://docs.astropy.org/en/stable/io/unified.html#built-in-readers-writers) and we could write our own reader/writer functions (http://docs.astropy.org/en/stable/io/registry.html#io-registry).

Using astropy.tables does impose a requirement that the format looks like a table.  Maybe this is too constraining or maybe not.  Depends on the type of information that we need to capture.

**Comment by jdtsmith** [comment]
One of my main goals is to make model packs easily parseable, human editable, and expressive (YAML seems perfect for this).  This becomes the main intereface for intermediate `PAHFIT` hackers.  But propagating constraints through to the output for record keeping is a worthy goal too.  And of course you could imagine doing a fit, tweaking one thing, redoing the fit, and so on.  

Simple constraints are easy to express in tabular form ([value, min,  ax]).  More complicated ties require some though, like “total integrated strength of features a,b, and c is equal to 0.4 x total integrated strength of features d, e, and f”.  I’m working on a way to express that compactly for input.  But maybe that kind of input coding can just pass through to the output.

**Comment by alexmaragko** [comment]
I have finished the read function. Currently it reads the output file created from the save function, and creates new dictionaries for all the components in a similar fashion to SciPackExGal, only now it uses the values stored in the output file.

Now the pmodel can be constructed from the output values and be the starting point for a new fit.

This means that we probably want to give the option in PAHFIT.py to either read the output file and not construct a model from the defaults, or go ahead and make a model from scratch as it currently does.

In addition, I've been working on the separate plot_pahfit.py which Karl suggested, in order to be able to remake the plot when reading the output file. @karllark  you suggested that the script should use the new read function, which it does, and the plotting function already written.

The problem with the last part is that the plot function is using the "if isinstance" statement to go through the different components in the model object. However, if someone wants to read the output file simply to plot the results, meaning that no model is going to be constructed, the plot function as it is should not work.

A possible solution to this would be to make a plotting Class within the plot_pahfit.py which will have two functions: The existing on which will be used when making a model object and running a fit, and a second one which will be used when loading results from the output file and will be adjusted to the read function dictionaries.

Let me know what you think.

**Comment by karllark** [comment]
Great to hear! 

As for the plotting question, I think we should see if there is a solution where the init function for the base PAHFIT object can be modified that if a file is given, it uses that file to make the dictionaries and then creates the pahfit model.  Then we could use the existing plot function.  The reason I suggest this is that if we keep a single plotting function, then we only have to maintain the code in one place.  If we have more than one plotting function, this will make it more complicated to maintain.

We can talk about this on Monday on the telecon at least.  :-)

**Comment by karllark** [comment]
I look forward to you pull request on this topic.  One way to move forward is to get your new code into the repository and I (or you or someone else) can work on the solution I mention in my previous comment.   Sometimes it is just easier to try coding it up to see if would work.  :-)

**Comment by karllark** [comment]
One idea would be to modify the init for PAHFITBase to take a scipack structure (with the dictionaries) or an input filename.  Then the read function could be used in the init function to create the scipack and then the existing init function code would create the model.  Would need to change the input parameters for the init function, but that is pretty straightforward.

**Comment by alexmaragko** [comment]
Ok I'll make a pull request including only the read function (excluding the plot_pahfit.py). Currently it is not called in any part of the main code. You can test it by making a basic run, get the output file, and then read it in ipython for example and call the read function.

**Comment by karllark** [comment]
This has been done via PR #43.  If a different version of the save file is desired, then a new issue should be opened with the details.
