### ISSUE TITLE
PAH fitting worse than last commit

### ISSUE THREAD

**Issue by Minnielam** [PAHFIT/pahfit#146]
Dear all,

I tried to fit IRS spectra by using PAHFIT python package. I found the PAH 7.7 um result from the lastest commit worse than the previous version that may be from a weaker S07 attenuation setting. Please see the figure below.

![image](https://user-images.githubusercontent.com/47394920/129509556-1a1513df-426e-427f-9e7d-0244b38c3d6e.png)

Thanks a lot for your help.

Bests,
Man I

**Comment by karllark** [comment]
Can you be more specific?  Are you fixing the attenuation to be zero?  This certainly appears so given the plot.  This was only possible with the latest commit - so what are you comparing it to to make the statement about the 7.7 feature?

**Comment by Minnielam** [comment]
@karllark Hi Karl, thanks a lot for your reply. I used the latest commit PAHFIT and old template, without changing any parameters (S07 is still a free parameter) from the previous version. I found the recovery of broad PAH feature 7.7um from latest version PAHFIT was weaker than the previous version.

**Comment by alexmaragko** [comment]
Did you happen to change the maximum number of iterations for the fit? Or, perhaps was the default maximum number different between versions, because I recall we changed that at some point from 400 to 1000. Maybe you could try to increase `fit_maxiter` and see if you get better results.

**Comment by ThomasSYLai** [comment]
@Minnielam It's good to know the limitation of PAHFIT. Given that PAHFIT is trained by a number of star-forming galaxies, it might not provide an ideal fitting result for certain other galaxies, such as heavily obscured AGNs or Seyfert 2 galaxies that exhibit strong silicate emissions. This is because only silicate absorptions are considered in the current version of PAHFIT. Based on the spectrum you provided, I believe there are silicate emissions at 9.7 and 18 µm. The reason for a poor fit at ~8 µm is due to the fact that silicate at 9.7 µm is not well constrained, since in this case, it might need to be treated as emission. My suggestion will be, use PAHFIT with caution for the spectra you have.

**Comment by Minnielam** [comment]
@ThomasSYLai Hi Thomas, thanks a lot for your constructive suggestion. Indeed, this is an obscured AGN which contains both SF and AGN emissions. Then, I will try to treat silicate emissions as an emission feature. 

Many thanks again for all your support and help~ @karllark @alexmaragko @ThomasSYLai 

Bests,
Man I

**Comment by Minnielam** [comment]
@karllark Hi Karl, thanks a lot for your help. In fact, I used the test template in the ~/pahfit/packs/ directory. I guess it is a general template for star-burst galaxies. 

 @alexmaragko Hi Alex, the fitting indeed has reached the maxfev value, which is show as follows:
WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
Number of calls to function has reached maxfev = 1000.
Now, I guess the first issue may be from the silicate emissions, so I will try the suggestion from Thomas. If the problem remains, I will update my comments.

Thank you again for all your efforts.

Bests,
Man I

**Comment by karllark** [comment]
Does the problem still remain?  Or has it been resolved and this issue can then be closed?

**Comment by Minnielam** [comment]
Hi @karllark, I assumed this problem is the limitation of PAHFIT as explained by @ThomasSYLai. Therefore, I treated the silicate emissions as the list of emissions. Then, the major problem solved. I think the comment could be closed now. Thanks a lot for everyone.

**Comment by karllark** [comment]
Thanks.  Glad it is working for you.
