### ISSUE TITLE
Add features in the AKARI wavelength coverage from 2.5-5 um

### ISSUE THREAD

**Issue by ThomasSYLai** [PAHFIT/pahfit#15]
Will add the features between 2.5-5 um in PAHFIT.
The parameters and constraints will be the same as the classic PAHFIT in IDL 1.6?

@jdtsmith Do we call our version of the IDL code that fits the AKARI spectra as 1.6?

**Comment by jdtsmith** [comment]
Do you mean the IDL-hacked version?  I'm not sure if we'll release that, but am open to discuss.

**Comment by els1** [comment]
These fit parameters in the 2.5-5um range will also be useful for the ISO adaptation.

**Comment by jdtsmith** [comment]
That sounds good.  We will make pre-relesase versions of the model pack that provides Akari coverage to help with building the ISO-based pack.
