### ISSUE TITLE
Mention in the docs that fwhm is not fractional

### ISSUE THREAD

**Issue by alexmaragko** [PAHFIT/pahfit#152]
Perhaps it is worth meentioning somewhere in the docs that the fwmh in the scipacks and the output file is not the fractional fwhm as in the IDL version, just to avoid confusion for people coming from IDL PAHFIT.

**Comment by jdtsmith** [comment]
I'd strongly suggest keeping them identical (fractional FWHM).  In practice random notes in the docs don't really get through to people, and if they look up the published equation for the model, they should expect it to be valid.

**Comment by els1** [comment]
I can see it would be useful to keep them the same but the astropy Drude profile we're using takes FWHM, not fractional FWHM.

**Comment by jdtsmith** [comment]
I see, but we can of course just translate on input/output outside of astropy, yes?  I guess the question comes down to whether consistency with the paper/old results vs. consistency with the AstroPy Drude model feature is more important.

**Comment by karllark** [comment]
I would vote for using the fwhm and not the fractional fwhm.  While fractional fwhm was used by PAHFIT previously, I would image that the fwhm value in physical units (micron) would be more useful in comparing with other works and lab measurements.  But my knowledge in this area is not extensive.  How have other fits to the PAH features been reported?  E.g. from ISO?  From Spitzer by using other methods than PAHFIT?

**Comment by els1** [comment]
I only know PAHFIT that uses fractional FWHM.
