### ISSUE TITLE
Release v2.0!

### ISSUE THREAD

**Issue by karllark** [PAHFIT/pahfit#166]
Release v2.0 is ready for release that the last pull request needed has been merged.

Ok with @jdtsmith and @els1?

**Comment by karllark** [comment]
Such a release will involve some direct commits to the master branch and various tags, etc.  As this is the first time, it may take me a little bit to do this.  I roughly follow the steps given [here](https://het.as.utexas.edu/HET/Software/Astropy-0.4.2/development/affiliated-packages.html#releasing-an-affiliated-package).

**Comment by jdtsmith** [comment]
Sounds good to me.  The only thing I'd wish for is a validation strategy to ensure each version is preserving the PAHFIT/IDL "classic" results in detail.  But I don't think that's urgent, and we can look at that for v2.1.  Thanks for your efforts.

**Comment by els1** [comment]
Yes!
