### ISSUE TITLE
Fixed-flavor PAH spectra

### ISSUE THREAD

**Issue by hwwspoon** [PAHFIT/pahfit#17]
We should define fixed-ratio PAH model spectra based on noise-free templates (Smith+07) to be used in the PAHFIT model. Especially useful for absorption-dominated spectra.

**Comment by karllark** [comment]
I think this request can be handled by having the ability to fix various parameters in the input science pack file.  If this is the case, then it should be handled soon.  But, we would want good docs and at least one example science pack for this case.  So leaving this issues open.

**Comment by jdtsmith** [comment]
We'll have to decide how many science model packs to "bless" with inclusion in PAHFIT.  I could imagine a low-flexibility mostly-fixed PAH model for low S/N spectra.

**Comment by jdtsmith** [comment]
This good idea is being pursued in terms of "one-to-many" and "many-to-many" ties, as well as power-based Gaussian/Drude features.
