### ISSUE TITLE
Blackbody continuum sum incorrectly implemented

### ISSUE THREAD

**Issue by jdtsmith** [PAHFIT/pahfit#171]
Looking closely at the model implementation, it seems the sum of blackbody continua is incorrectly implemented.  Here is the PAHFIT model in simple form:

![httptir astro utoledo edujdsmithresearchdownloadpah_template_final_apj pdf](https://user-images.githubusercontent.com/93749/160857161-aadf5d15-1d8e-4dc4-af48-3f3ba16ac70b.jpeg)

Notice the B_nu/lam^2, which is a sum of emissivity=2 MBB's.  I believe the current model continuum sources are unmodified (which makes them "peakier" and thus a bit harder to define smooth continuum with). 

This brings up the need to validate against IDL PAHFIT not just in terms of the fit quality, but also the fit _parameters_ including the tau's in the above.  

I will take a crack at fixing this, probably by adding a "Modified" flag to the Blackbody1D model component and an associated column to the scipacks.  Or perhaps just make a `ModifiedBlackBody1D` derived model.  

Can someone take a look and confirm my suspicion here?

**Comment by jdtsmith** [comment]
Update: on even closer look, it seems the `BlackBody1D` model is **not** in fact a Blackbody, but a MBB.  This means that the _starlight_ which is not supposed to be modified (stars don't have strong frequency dependence of their emissivity) is the one that is incorrect.  Which is less severe, but still incorrect.  I'll put together a PR.

**Comment by karllark** [comment]
Can you comment on your implementation?  In a previous comment you say that the current "BlackBody1D" is actually a modified blackbody.  But then in your next comment you are modifying the currenct BlackBody1D.  Feeling a bit confused.

**Comment by jdtsmith** [comment]
Yep I altered BlackBody1D to be an actual BB, then added an MBB which calls it.
