### ISSUE TITLE
Create separate instrument packs & science packs

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#183]
Currently instrument and science packs are integrated in a single pack. Need to split information set by instrument from information unique for science case. 

Instrument packs should allow spectral resolution changing w/ wavelength (possible using additional files, or a resolution model). Also include min/max wavelengths for each instrument (can be by each spectral segment in an instrument too)

Requires defining intrinsic widths of lines in science pack and “spectral breaks”.

See also issue #16.

**Comment by jdtsmith** [comment]
Handled by #226 and #233.  Important point to note: redshift is handled as follows:

1. Lines are redshifted into the observed frame.
2. FWHM calculated.
3. Spectrum is de-redshifted into the rest frame.
4. FWHM is scaled by 1/(1+z).
