### ISSUE TITLE
Covariance: fix using Hessian Matrix in post-process

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#185]
Currently, scipy does not always return errors. See #149 
Try quick fix: take auto-derivative

**Comment by jdtsmith** [comment]
@Arafraza  (David Carroll) is going to help out with the Hessian matrix covariance method for his final project for "Computational Physics".

**Comment by jdtsmith** [comment]
Unfortunately David's exercise showed that the canonical packages to estimate the Hessian with our model function are very slow: many hours to run.  So possibly a dead end.  Will leave open in case we have any other thoughts.

**Comment by jdtsmith** [comment]
I'm closing this since it hasn't panned out.
