### ISSUE TITLE
Implement the use of JointFitter (in astropy)?

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#190]
input multiple spec with each their pack, information which parameters need to be the same in all spec. [https://docs.astropy.org/en/latest/modeling/jointfitter.html]

JD: "if using the joint fitter, we’ll be making more than one model for simul-fitting.  I think this means we should create and keep a separate parameter table for all the input channels/segments/orders/whatever we call them." <-- Related to PR#165

Use AKARI + Spitzer as a test run ….

**Comment by jdtsmith** [comment]
This makes the JointFitter kind of problematic for PAHFIT at the moment:

> The JointFitter uses the scipy.optimize.leastsq. In addition, it **does not support fixed, bounded, or tied parameters at this time**

But it's so much simpler to conceptualize than "figure out a way to blend your spectral segments".

**Comment by karllark** [comment]
I am pretty sure the JointFitter can be enhanced to support fixed, bounded, and tied parameters.  It has not been as fully developed as other fitters.

**Comment by karllark** [comment]
And this is what the JointFitter does for us.  It just needs to get a little work to bring it up to the same standard as the LevMar fitter that is already there.  I'm pretty sure there are even existing helper routines that can be used to do most of this work.  This is even something I could try to do if it is a real priority for PAHFIT.  And if we upgrade JointFitter, then everyone can get the benefit.

**Comment by jdtsmith** [comment]
Closing in favor of #291.
