### ISSUE TITLE
Validation of newer versions

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#196]
Write code to automatically compare all parameters between different versions of PAHFIT for a test spectrum.

**Comment by jdtsmith** [comment]
Including FWHM, amplitudes, positions, etc.   Just comparing the fit may not be sufficient. Could just fit the M101 central spectrum with IDL PAHFIT and tabulate those value.

**Comment by karllark** [comment]
We did already go down this route.  The degeneracies meant that we didn't always get great comparisons while we were getting great fits.
