### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jdtsmith** [PAHFIT/pahfit#22]
I'm a strong proponent of GPL licenses.  IDL PAHFIT is license under GPLv2, and I think that or GPL3 are ideal for what we're trying to achieve.  Are there license requirements for AstroPy affiliation?

**Comment by karllark** [comment]
There are no requirements for licenses for astropy affiliation that I am aware of.

There has been a movement away for the GPL license as it makes it can make it harder for future work where not all the developers can be reached anymore.  Astropy uses the BSD licence and I've been adopting this for packages I develop.  Partly as I don't really care and the astropy core people have put a lot of thought/discussion into the choice of a license.

http://docs.astropy.org/en/stable/license.html

**Comment by karllark** [comment]
The BSD license is currently what the pahfit repository has.  Mainly as this is what I put in a year ago when setting up the repository.  We definitely can change it.

https://github.com/PAHFIT/pahfit/blob/master/LICENSE

**Comment by karllark** [comment]
At a minimum, we should change it to have the 'PAHFIT developers' as the copyright holders (not me).

**Comment by jdtsmith** [comment]
I'm in favor of changing to the GPLv2 for continuity with original PAHFIT, and in the sense that this could be considered a derived work.  No real difference for the end user. Happy to make that change if people agree.
