### ISSUE TITLE
weird test issue

### ISSUE THREAD

**Issue by jdtsmith** [PAHFIT/pahfit#251]
Does anyone familiar with the CI setup here understand this issue?  Seems to be recurring for most of our tests. 

```
py310-cov: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'HOME WINDIR LC_ALL LC_CTYPE CC CI TRAVIS'
```

**Comment by karllark** [comment]
This a new error and I'm seeing it on other repositories of mine.  I'll investigate.
