### ISSUE TITLE
Issue with compatibility with Astropy -- I think

### ISSUE THREAD

**Issue by jkeohane** [PAHFIT/pahfit#262]
I have just installed pahfit and am working with Spitzer IRS data.  I am trying to go through the tutorial, but I am having issues.
I am running the current Astropy -- 

s = spectra[0]
from pahfit.model import Model
model = Model.from_yaml('classic.yaml')
#s.meta['instrument'] = 'spitzer.irs.*.[12]'
s.meta['instrument'] = "spitzer.irs.sl.1"
s.set_redshift_to(0)
s.mask = np.zeros(s.shape, dtype=bool)
model.guess(s)
model.fit(s)
model.plot(s)

Then I get lots of errors:

File ~/anaconda3/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Dropbox/G11.2/Python_Code/SL1_on_H2_shell_with_BG_Subtraction.py:156
    model.guess(s)

  File ~/anaconda3/lib/python3.10/site-packages/pahfit/model.py:174 in guess
    param_info = PAHFITBase.estimate_init(xz, yz, param_info)

  File ~/anaconda3/lib/python3.10/site-packages/pahfit/base.py:794 in estimate_init
    amp_guess = sp(lam) / bb(lam)

  File ~/anaconda3/lib/python3.10/site-packages/scipy/interpolate/_polyint.py:80 in __call__
    y = self._evaluate(x)

  File ~/anaconda3/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:752 in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)

  File ~/anaconda3/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:781 in _check_bounds
    raise ValueError("A value ({}) in x_new is below "

ValueError: A value (5.5) in x_new is below the interpolation range's minimum value (7.533706).

Then, when I make a new .yaml model file with only the H_2 spectral lines, I get:

Traceback (most recent call last):

  File ~/anaconda3/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Dropbox/G11.2/Python_Code/SL1_on_H2_shell_with_BG_Subtraction.py:156
    model.guess(s)

  File ~/anaconda3/lib/python3.10/site-packages/pahfit/model.py:173 in guess
    param_info = self._kludge_param_info(inst, z)

  File ~/anaconda3/lib/python3.10/site-packages/pahfit/model.py:433 in _kludge_param_info
    param_info = PAHFITBase.parse_table(self.features)

  File ~/anaconda3/lib/python3.10/site-packages/pahfit/base.py:665 in parse_table
    _ingest_limits(

  File ~/anaconda3/lib/python3.10/site-packages/pahfit/base.py:47 in _ingest_limits
    mask_min = min_vals.mask

AttributeError: 'Column' object has no attribute 'mask'

Then I noticed that some of the Column attributes changed with Astropy v. 4.   Perhaps that is why?

Thanks for the help

-- Jonathan

**Comment by drvdputt** [comment]
The issue with the guess for certain wavelength ranges is known (e.g. https://github.com/PAHFIT/pahfit/issues/260), and should be fixed with an update to the guess function (#242).

I am aware that a minimum astropy version is required. Should be simple fix in the package configuration. Have you tried updating your astropy, or you know at which version it starts working?

**Comment by drvdputt** [comment]
The new guess function #242 has now been merged. So that should resolve one of your problems. Any update on the astropy / column mask issue?
