### ISSUE TITLE
Atomic lines fitting too narrow

### ISSUE THREAD

**Issue by sophfb** [PAHFIT/pahfit#263]
When trying to fit MIRI JWST spectra using PAHfit, I am having an issue where the lines are fitting too narrow. I tried suggestions of setting the instrument_fwhm = False and then setting my own values and bounds for the fwhm's of the atomic lines I was trying to fit, but that resulted in the same fits. Is there any reason this could be?

Below is the ArII line, which was fit and plotted after changing the fwhm manually by editing the features table, also shown below.

model_fls1_edit.features.loc['[ArII]']['fwhm'][0] = 0.053
model_fls1_edit.features.loc['[ArII]']['fwhm'][1:] = [0.0265, 0.0795]

![Figure 23 (1)](https://github.com/PAHFIT/pahfit/assets/56405996/30d96a15-f7b1-4607-b765-ec977d727b24)

**Comment by drvdputt** [comment]
I did a quick test, and if I apply e.g.
```
model.features.loc['[FeII]_35']['fwhm'][1:] = (0.1, 0.5)
```
between `guess()` and `fit()`, the fwhm changes from the instrument-based value of 0.3387, to 0.3384. So there should be no nothing that stops the fitting of the FWHM by construction.

In your case, you might be stuck in a local minimum, or the impact on chi^2 by the changes in FWHM are not big enough for the fitter to find the right direction. For your data, a multi-component fit might be necessary, for which there is currently no obvious way in PAHFIT.

**Comment by jdtsmith** [comment]
Stay tuned for the possibility to add another component (with velocity offset, broadening).
