### ISSUE TITLE
Bounds as optional

### ISSUE THREAD

**Issue by karllark** [PAHFIT/pahfit#27]
Update the base class to allow for bounds to be optional.
If not in input feature dictionary, then set to (None, None).
Probably should add helper functions in this code area to make it easier to do this (less copying).

**Comment by jdtsmith** [comment]
Are we talking fixed bounds?  Like width can be from x..y?  Or parametric/tied bounds, e.g. "some interesting combination of this set of parameters must match another interesting combination of another set of parameters, within 10%".  We will eventually need that more robust kind of constraint input from the science model pack.

**Comment by karllark** [comment]
Here I was thinking fixed bounds, but it could be any kind of bounds.  Why I would want to run PAHFIT without some kind of bounds I'm not sure, but something we could do.  The setup I'm currently working on could be modified to support this, but currently it requires bounds of some sort.

**Comment by jdtsmith** [comment]
Some features of the model are fixed (unchanging).  Most would (and should) vary within limits.  The idea of multi-parameter tied limits is very appealing (best usage case: tie the integrated intensities of different feature complexes, each involving 6 or more parameters).

Fixed:

```
T_star
T_dust[300.0K]
T_dust[200.0K]
T_dust[135.0K]
T_dust[90.0K]
T_dust[65.0K]
T_dust[50.0K]
T_dust[40.0K]
T_dust[35.0K]
dust_feature_lambda[5.3]
dust_feature_frac_fwhm[5.3]
dust_feature_lambda[5.7]
dust_feature_frac_fwhm[5.7]
dust_feature_lambda[6.2]
dust_feature_frac_fwhm[6.2]
dust_feature_lambda[6.7]
dust_feature_frac_fwhm[6.7]
dust_feature_lambda[7.4]
dust_feature_frac_fwhm[7.4]
dust_feature_lambda[7.6]
dust_feature_frac_fwhm[7.6]
dust_feature_lambda[7.8]
dust_feature_frac_fwhm[7.8]
dust_feature_lambda[8.3]
dust_feature_frac_fwhm[8.3]
dust_feature_lambda[8.6]
dust_feature_frac_fwhm[8.6]
dust_feature_lambda[10.7]
dust_feature_frac_fwhm[10.7]
dust_feature_lambda[11.2]
dust_feature_frac_fwhm[11.2]
dust_feature_lambda[11.3]
dust_feature_frac_fwhm[11.3]
dust_feature_lambda[12.0]
dust_feature_frac_fwhm[12.0]
dust_feature_lambda[12.6]
dust_feature_frac_fwhm[12.6]
dust_feature_lambda[12.7]
dust_feature_frac_fwhm[12.7]
dust_feature_lambda[13.5]
dust_feature_frac_fwhm[13.5]
dust_feature_lambda[14.0]
dust_feature_frac_fwhm[14.0]
dust_feature_lambda[14.2]
dust_feature_frac_fwhm[14.2]
dust_feature_lambda[15.9]
dust_feature_frac_fwhm[15.9]
dust_feature_lambda[16.4]
dust_feature_frac_fwhm[16.4]
dust_feature_lambda[17.0]
dust_feature_frac_fwhm[17.0]
dust_feature_lambda[17.4]
dust_feature_frac_fwhm[17.4]
dust_feature_lambda[17.9]
dust_feature_frac_fwhm[17.9]
dust_feature_lambda[18.9]
dust_feature_frac_fwhm[18.9]
dust_feature_lambda[33.1]
dust_feature_frac_fwhm[33.1]
tau_9.7
Beta_Extinct
Curve_Type
Screen
```

Lower limit only:
```
tau_star
tau_dust[300.0K]
tau_dust[200.0K]
tau_dust[135.0K]
tau_dust[90.0K]
tau_dust[65.0K]
tau_dust[50.0K]
tau_dust[40.0K]
tau_dust[35.0K]
line_central_inten[H2 S(7)]
line_central_inten[H2 S(6)]
line_central_inten[H2 S(5)]
line_central_inten[[ArII]]
line_central_inten[H2 S(4)]
line_central_inten[[ArIII]]
line_central_inten[H2 S(3)]
line_central_inten[[SIV]]
line_central_inten[H2 S(2)]
line_central_inten[[NeII]]
line_central_inten[[NeIII]]
line_central_inten[H2 S(1)]
line_central_inten[[SIII] 18]
line_central_inten[[OIV]]
line_central_inten[[FeII]]
line_central_inten[H2 S(0)]
line_central_inten[[SIII] 33]
line_central_inten[[SiII]]
dust_feature_central_inten[5.3]
dust_feature_central_inten[5.7]
dust_feature_central_inten[6.2]
dust_feature_central_inten[6.7]
dust_feature_central_inten[7.4]
dust_feature_central_inten[7.6]
dust_feature_central_inten[7.8]
dust_feature_central_inten[8.3]
dust_feature_central_inten[8.6]
dust_feature_central_inten[10.7]
dust_feature_central_inten[11.2]
dust_feature_central_inten[11.3]
dust_feature_central_inten[12.0]
dust_feature_central_inten[12.6]
dust_feature_central_inten[12.7]
dust_feature_central_inten[13.5]
dust_feature_central_inten[14.0]
dust_feature_central_inten[14.2]
dust_feature_central_inten[15.9]
dust_feature_central_inten[16.4]
dust_feature_central_inten[17.0]
dust_feature_central_inten[17.4]
dust_feature_central_inten[17.9]
dust_feature_central_inten[18.9]
dust_feature_central_inten[33.1]
```

Lower and upper limit:

```
line_lambda[H2 S(7)]
line_frac_fwhm[H2 S(7)]
line_lambda[H2 S(6)]
line_frac_fwhm[H2 S(6)]
line_lambda[H2 S(5)]
line_frac_fwhm[H2 S(5)]
line_lambda[[ArII]]
line_frac_fwhm[[ArII]]
line_lambda[H2 S(4)]
line_frac_fwhm[H2 S(4)]
line_lambda[[ArIII]]
line_frac_fwhm[[ArIII]]
line_lambda[H2 S(3)]
line_frac_fwhm[H2 S(3)]
line_lambda[[SIV]]
line_frac_fwhm[[SIV]]
line_lambda[H2 S(2)]
line_frac_fwhm[H2 S(2)]
line_lambda[[NeII]]
line_frac_fwhm[[NeII]]
line_lambda[[NeIII]]
line_frac_fwhm[[NeIII]]
line_lambda[H2 S(1)]
line_frac_fwhm[H2 S(1)]
line_lambda[[SIII] 18]
line_frac_fwhm[[SIII] 18]
line_lambda[[OIV]]
line_frac_fwhm[[OIV]]
line_lambda[[FeII]]
line_frac_fwhm[[FeII]]
line_lambda[H2 S(0)]
line_frac_fwhm[H2 S(0)]
line_lambda[[SIII] 33]
line_frac_fwhm[[SIII] 33]
line_lambda[[SiII]]
line_frac_fwhm[[SiII]]
```

**Comment by karllark** [comment]
Are the lists reflecting what is in PAHFIT v1.2 or what you think should be the "bugfixed" v2.0 version?

**Comment by karllark** [comment]
Looking at the IDL code again, I see that I missed that there are parameters that have code with bounds, but these are commented out and the fixed keyword added.  
Clearly, we need to vet which parameters are fixed and which are bounded for the v2.0 model based on the v1.2 model.  This should be in the Exgal science pack setup (for Spitzer?).

Tying features could be very powerful.  But this should be for post v2.0 development I think.

When I raised this issue, I was mainly thinking about adding code to allow for the bounds to be optional.  Sounds like this may not be a good idea.  So, should we force each science pack to provide bounds for all the parameters that are not fixed?  And provide a boolean stating if the parameter is fixed?

**Comment by jdtsmith** [comment]
This is current PAHFIT, v1.4.  Some things should be dropped, for example 18.9 (C60) and 33µm (predicted graphitic band that never materialized).  But now I actually think perhaps PAHFIT classic should include all of PAHFITs warts, then we can pretty quickly recommend people don't use it once other model packs are tested and available. 

There are couple cases where we experimented with bounds then ended up fixing them (the ultimate boundedness).  In order of preference for a model like PAHFIT are:

1. Fixed Parameters
2. Bracketed Parameters (bounded on both sides, either simplistically or via a parameter tie)
3. One-side bounded parameters (again either simply (">0') or more complicated constraint).
4. Unbounded parameters (scary)

Science-guided bounds are basically essential to quality fits when S/N suffers.  So absolutely, science model packs should include information on bounds, especially things like complex parameter ties (e.g. integrated strength of 7.7µm Complex to 17µm Complex is fixed without some bracketing range like 10%).  This will help quite a bit when S/N is low and/or complicated dust attenuation is dramatically altering the spectrum. 

In addition,  _instrument packs_ should specify some relevant bounds, e.g. widths and positional accuracy for unresolved lines.  Akari for example has a fairly "loose" wavelength calibration, so you have to give a bit more wiggle room.  

If bounds are more than just `[low,high]`, which they will need to be, we need to come up with a plan of how to express those.  I've been considering a `YAML` file format that is simple but expressive for this stuff.  Probably we should start a new issue and just mock it up and iterate.

**Comment by els1** [comment]
@jdtsmith Why do you want to drop the 18.9 C60 band?

**Comment by jdtsmith** [comment]
We could keep it , but at the time I included it I thought it was a PAH feature.   There are 3 other active bands as well, but they are much more challenging to include.  

--

**Comment by karllark** [comment]
We can keep it.  But, Do we consider C60 as dust?  Or gas?  This impacts what feature width would be expected (intrinsically broad or at the instrumental resolution)?

**Comment by jdtsmith** [comment]
It behaves like a PAH and has intrinsic breadth, but I’d consider keeping it only in one of the special/Galactic model packs.  Or the best would be a C60+C70 pack that ~fixes much of the rest of band ratios.  That’s pretty specialized though.  

--
