### ISSUE TITLE
features.util.bounded_is_fixed() does not work for dust_feature-only science packs

### ISSUE THREAD

**Issue by drvdputt** [PAHFIT/pahfit#274]
When a science pack is created that only has dust_feature entries, there will be no masked values in the power column of the Features table. As a consequence, the astropy table constructor automatically decides whether to use a `Column` instead of a `MaskedColumn`. This means that any functionality that relies on the presence of a mask attribute, wil fail.

E.g. in `featuresutil.bounded_is_fixed(): return ma.getmask(val)[..., -2:].all(-1)`, where `getmask` will return `False`.

Most consistent solution: Force the use of `MaskedColumn` (or in our case `BoundedMaskedColumn`) when the Features table.

Even if we found another way around this bug, I think we should enforce this to ensure consistency. (e.g. What if the user want to set power boundaries, but the power column does not support masks because of the way the table was loaded?)

**Comment by jdtsmith** [comment]
I agree we can just enforce all columns are `BoundedMaskedColumns` even if most of the elements are "fixed".

**Comment by jdtsmith** [comment]
OK, update, never mind that.  #283 includes a fix for this.  It should create bounds for all parameter columns except for string-parameters (`name`, `group`, `model`, `geometry`).  The latter should never be passed to the bounds checker functions.

**Comment by drvdputt** [comment]
Yes, seems to work now, since `BoundedMaskedColumn` doesn't exist anymore, this bug can also no longer appear.

**Comment by jdtsmith** [comment]
I didn't check all the `utils` convenience functions but we can revisit if needed.
