### ISSUE TITLE
Unit of the output power and 

### ISSUE THREAD

**Issue by AstroAvijit** [PAHFIT/pahfit#275]
The unit of the output power is W/m^2 or W/m^2/Hz when the input flux is in Jy?

**Comment by drvdputt** [comment]
In the near future, yes, give or take a few factors of 10. See discussion here https://github.com/PAHFIT/pahfit/issues/28.
The "real" power units have an example implementation in my experimental branch (https://github.com/drvdputt/pahfit/tree/experimental).

For the current master branch, "power" is actually the amplitude of the feature. So if your input flux is in Jy, then the values in the power column of the output are also in Jy.
