### ISSUE TITLE
Where to host notebooks?

### ISSUE THREAD

**Issue by drvdputt** [PAHFIT/pahfit#276]
The current example notebooks are still hidden somewhere in the jwebbinar repo (https://github.com/spacetelescope/jwebbinar_prep). To make matters more complicated, the updated notebook is found in my fork of the same repo. 

We should have a dedicated space to host these notebooks (regardless of whether it's a live ipython notebook environment, or just a file download).

A couple of suggestions
- In a directory "notebooks" of the main pahfit repo. 
  Advantage: can ensure that the notebooks are kept up to date at every commit.
  Disadvantage: introduces dependencies on jupyter, need for sample data. 
- In a separate repository (e.g. PAHFITbooks). 
  Advantage: we can add dependencies and extra materials as we wish, without affecting PAHFIT itself.
  Disadvantage: at every PAHFIT update, we need to remember to update these notebook. And we need to write separate install instructions, some documentation/overview of the notebooks.

**Comment by jdtsmith** [comment]
Best would be somewhere live!

**Comment by drvdputt** [comment]
I have created this https://github.com/drvdputt/PAHFITbooks, where two notebooks can be downloaded with some extra tools. 

For the live hosting, we can look into Binder, I remember that there was an astropy workshop that used it. https://mybinder.org/v2/gh/astropy/astropy-workshop/HEAD

**Comment by jdtsmith** [comment]
Great.  Why not host these under the PAHFIT organization on GH?  I'm happy to create a repo and make you co-owner.

**Comment by jdtsmith** [comment]
Just created https://github.com/PAHFIT/PAHFITBooks and made you a maintainer.  Private for now and we can open it when we are good with the setup.

**Comment by drvdputt** [comment]
Good, I have pushed my main branch to this repo. Keeping the one one drvdputt around for now, for sharing. We should add a link to PAHFIT/PAHFITbooks (and any live hosting if we have it) in the readme of PAHFIT once it goes public.

**Comment by jdtsmith** [comment]
Sounds good.  I'll close this for now, can reopen one later for live notebooks.
