### ISSUE TITLE
Spitzer based test code

### ISSUE THREAD

**Issue by karllark** [PAHFIT/pahfit#3]
Should start with getting the code running on Spitzer IRS data.
Check the results with the IDL code results

**Comment by karllark** [comment]
A minimum need a test against the fit parameters returned by IDL code.

**Comment by jdtsmith** [comment]
I can provide a set of fits for a small selection of galaxy spectra.  Then we can build tests on returned feature strengths, ratios among them, silicate opacity, etc.  This will be very revealing.

**Comment by karllark** [comment]
Sounds great.  I can help by building the tests for such spectra.

**Comment by karllark** [comment]
@jdtsmith : can you provide me with a galaxy spectrum with the returned feature strengths?  I can then put together a test.  We can always expand to more spectra later in such tests, but thought it would be good to get started with a single one.

**Comment by els1** [comment]
@karllark I can give you a spectrum + IDL pahfit output of NGC2023 (5-15um) if you want. We also have these of M33/M83 HII regions but they are a combination of SH (10-20) +SL (5-3x) spectra.

**Comment by karllark** [comment]
Let's start with NGC 2023.  You can send it to me via email or add it as a comment on this thread.

**Comment by els1** [comment]
Attached a nice spectrum of NGC2023 (Fig. 2 in Peeters+2017) with PAHFIT results (saved as 'xdr' in IDL). 
It seems I constrained the fit as follows: no star light, no extinction, no fs lines, no H2 S(6) and S(7) lines, and tau_dust at 35, 40, 50, 65, and 90K fixed at zero. If you want the results of a default PAHFIT, I can run it as well. 

[ngc2023_pahfit_Fig2Peeters2017.xdr.gz](https://github.com/PAHFIT/pahfit/files/2870639/ngc2023_pahfit_Fig2Peeters2017.xdr.gz)
[ngc2023_sp_Fig2Peeters2017.dat.gz](https://github.com/PAHFIT/pahfit/files/2870640/ngc2023_sp_Fig2Peeters2017.dat.gz)

**Comment by els1** [comment]
As IDL PAHFIT was developed for nearby galaxies, a fair comparison would be to restrict the sample for comparison of v2.0 with IDL PAHFIT to ISM-type sources (galaxies, PDRs).
Issue #76 raises issues of IDL PAHFIT with other type of sources.

**Comment by karllark** [comment]
Working on this today.  Will add a test for the M101 nucleus at a minimum.

**Comment by karllark** [comment]
Closing as basics done with PR #113.

Additional tests should each get their own issue to make them easier to track.
