### ISSUE TITLE
Extra model components usage

### ISSUE THREAD

**Issue by alexmaragko** [PAHFIT/pahfit#42]
As I was working on the Table output function I realized that 2 identical model components are used when building the final model.

In both cases it's the first element in the H2 features and ionic features lists (H2 S(7) and [ArII] respectively).

Currently, the final model has 55 components. However, there are 9 blackbodies, 25 dust features, 8 H2 features, 10 ionic features, and 1 component for the tau of the attenuation curve, adding up to 53 components in total.

**Comment by karllark** [comment]
Can you identify how the duplicate components were added?  Is this an easy fix?

**Comment by alexmaragko** [comment]
I think I found something. 
When building the model in PAHFITBase.py the loops in lines 127 and 160 are:

for k in range(n_h2): , and  
for k in range(n_ion): respectively.

And they should probably be: 
for k in range(1, n_h2): , and 
for k in range(1, n_ion): 

just like the loop for blackbodies:
for k in range(1, n_bb):

**Comment by alexmaragko** [comment]
Yes, that did the trick. I just tested it.
