### ISSUE TITLE
Create an easy access to individual components data

### ISSUE THREAD

**Issue by rayssags** [PAHFIT/pahfit#60]
Currently the access to the model of the individual components requires a bit of work so I think it would be very useful to create a class that has the components as attributes. From what I've seen of the `plot_pahfit.py`, it would be only a matter of adapting some things but #19 makes me question if it is that simple.
This would make it easier to work directly with the fitted data in operations such as plotting specific components or just saving the individual components for another use -- e.g.: the dust features can be used as input for the NASA Ames PAH IR Spectroscopic Database. In addition to the components as attributes there could be a method that allows saving everything in a neat table.

**Comment by karllark** [comment]
Not quite sure what you mean here.  Do you want to be able to identify which component is a PAH feature? 
 Or is this something else?  Can you give an example?

**Comment by karllark** [comment]
There is a save function already and it does create a table.  (see https://pahfit.readthedocs.io/en/latest/fit_spectrum.html).  Do you have an idea for a different type of table?

**Comment by karllark** [comment]
This should be enabled by the capability discussed in issue #19.  Closing this issue.  Please reopen if this is not the case.
