### ISSUE TITLE
'Drude1D' object has no attribute 'stddev'

### ISSUE THREAD

**Issue by B1GeasY** [PAHFIT/pahfit#64]
Hi, sorry I got a problem when I tried to run the pahfit, my astropy version is 4.0 and pahfit is 2.0.dev96

here is my command:
run_pahfit M101_Nucleus_irs.ipac scipack_ExGal_SpitzerIRSSLLL.ipac

And I got these messeges:
WARNING: AstropyDeprecationWarning: Class BlackBody1D defines class attributes ``inputs``.
            This has been deprecated in v4.0 and support will be removed in v4.1.
            Starting with v4.0 classes must define a class attribute ``n_inputs``.
            Please consult the documentation for details.
             [astropy.modeling.core]
WARNING: AstropyDeprecationWarning: Class BlackBody1D defines class attributes ``inputs``.
            This has been deprecated in v4.0 and support will be removed in v4.1.
            Starting with v4.0 classes must define a class attribute ``n_inputs``.
            Please consult the documentation for details.
             [astropy.modeling.core]
Traceback (most recent call last):
  File "/Users/k/anaconda3/bin/run_pahfit", line 90, in <module>
    pmodel = PAHFITBase(filename=packfile)
             │                   └ '/Users/k/anaconda3/lib/python3.7/site-packages/pahfit/packs//scipack_ExGal_SpitzerIRSSLLL.ipac'
             └ <class 'pahfit.base.PAHFITBase'>
  File "/Users/k/anaconda3/lib/python3.7/site-packages/pahfit/base.py", line 166, in __init__
    'stddev': dust_features['fwhms_fixed'][k]})
  File "/Users/k/anaconda3/lib/python3.7/site-packages/astropy/modeling/core.py", line 441, in __init__
    __init__, args, kwargs, varkwargs='kwargs')
  File "/Users/k/anaconda3/lib/python3.7/site-packages/astropy/modeling/core.py", line 438, in __init__
    return super(cls, self).__init__(*params, **kwargs)
                 │    │               │         └ {'amplitude': 100.0, 'x_0': 5.27, 'fwhm': 0.17918, 'name': 'DF0', 'bounds': {'amplitude': (0.0, None), 'x_0': (5.17, 5.369999999...
                 │    │               └ ()
                 │    └ <Drude1D(amplitude=1., x_0=10., fwhm=1., name='DF0')>
                 └ <class 'pahfit.component_models.Drude1D'>
Name: Drude1D
N_inputs: 1
N_outputs: 1
Fittable parameters: ('amplitude', 'x_0', 'fwhm...
  File "/Users/k/anaconda3/lib/python3.7/site-packages/astropy/modeling/core.py", line 715, in __init__
    self._initialize_constraints(kwargs)
    │                            └ {'amplitude': 100.0, 'x_0': 5.27, 'fwhm': 0.17918, 'bounds': {'amplitude': (0.0, None), 'x_0': (5.17, 5.369999999999999), 'fwhm'...
    └ <Drude1D(amplitude=1., x_0=10., fwhm=1., name='DF0')>
  File "/Users/k/anaconda3/lib/python3.7/site-packages/astropy/modeling/core.py", line 1801, in _initialize_constraints
    param = getattr(self, ckey)
    │               │     └ 'stddev'
    │               └ <Drude1D(amplitude=1., x_0=10., fwhm=1., name='DF0')>
    └ Parameter('x_0', value=10.0)
AttributeError: 'Drude1D' object has no attribute 'stddev'

Is there a solution about this problem?

**Comment by B1GeasY** [comment]
Ok I got this. In source code base.py file, line 166, just replace the 'stddev' with 'fwhm'.

**Comment by karllark** [comment]
Thanks for raising the issue.  Not sure in detail how you fixed this.  Note that v4.0 of astropy made changes and updates to pahfit needed as a result.  I've created an issue for this.  See #65.
