### ISSUE TITLE
error: [Errno 13] Permission denied on installation

### ISSUE THREAD

**Issue by alexmaragko** [PAHFIT/pahfit#66]
I'm trying to re-install pahfit from within a new branch containing updated files regarding issue #65, but when running `python setup.py install` from my astroconda environment I get the following error:

running install
running bdist_egg
running egg_info
error: [Errno 13] Permission denied

**Comment by karllark** [comment]
I can try to see if pahfit installs for me with the current master branch and your new branch (once you put in the PR).  It will be a few days before I can do this.

**Comment by karllark** [comment]
I am able to install from your branch no problem.  Are you using a conda environment?  Or just in your system?  I am in a conda environment, so don't need root access to install.

**Comment by karllark** [comment]
Note that updating to the astropy provide BlackBody model might be complicated.  It returns the calculation with units and that will probably be an issue as mixing models with and without units is non-trivial.  Might want to just do this PR for Drude1D and fixing the n_inputs warning.  If you can solve the BlackBody units thing, then great.  Just a warning that this may be interesting.

**Comment by alexmaragko** [comment]
> I am able to install from your branch no problem. Are you using a conda environment? Or just in your system? I am in a conda environment, so don't need root access to install.

Yes I'm using a conda environment. The issue was my initial installation was system-wide, and certain directories had root ownership and group. Changing those to user, resolved it.

**Comment by alexmaragko** [comment]
> Note that updating to the astropy provide BlackBody model might be complicated. It returns the calculation with units and that will probably be an issue as mixing models with and without units is non-trivial. Might want to just do this PR for Drude1D and fixing the n_inputs warning. If you can solve the BlackBody units thing, then great. Just a warning that this may be interesting.

I'll make some trial runs and play around with the units to check issues . If it gets too complicated I'll go ahead with a PR without the BlackBody model for the time.

**Comment by karllark** [comment]
Great to hear your install issues have resolved.  Looking forward to an updated PR.

**Comment by karllark** [comment]
Closing as this issue has been addressed.
