### ISSUE TITLE
PAHFIT run time test

### ISSUE THREAD

**Issue by ThomasSYLai** [PAHFIT/pahfit#74]
The latest version of PAHFIT in python runs slower than the original PAHFIT in IDL. 
Need to investigate where the bottleneck is in the code. Likely to be the compound model in astropy.modeling.
It is also worth investigating whether the refactor of astropy v4.0+ makes the code slow.

**Comment by jdtsmith** [comment]
What was the approximate slowdown, and how much faster is IDL now (for the ~same complexity of spectrum and model)?

**Comment by karllark** [comment]
I can now *confirm* that the slowdown is to do with the new version of astropy.  

Created a conda environment with python 3.7 and astropy 3.2.3.  Minor changes to the current pahfit code to get things to work (basically copying the astropy Drude1D into the component model).

Speed in astropy 3.2.3: 4.5 sec.
Speed in astropy 4.2   : 50 sec.

200 iterations in both cases.

Blargh.

I will now profile the code both ways and see what the change is.  I'm very suspicious that it is all in the astropy modeling refactor that happened with astropy 4.0.

Progress.

**Comment by jdtsmith** [comment]
Nice find (and ouch!).  <10s is pretty reasonable.  Complexity will go way up as JWST spectra will have 10x the spectral samples, but good start.

**Comment by karllark** [comment]
Complexity is going to be insane!  The number of gas lines from PDRs at 3000 res is scary large in PDR/HII models.

**Comment by jdtsmith** [comment]
One simple trick is just to use a global counter to see how many function evaluations happened. Since gradients are estimated numerically, gradients per iteration might have changed.

**Comment by karllark** [comment]
I've opened the issue on astropy. https://github.com/astropy/astropy/issues/11314

I've done some profiling (see the astropy issue) and it does not look to be about the compound model.  Not quite sure what the problem it, but it maybe in how the parameters are handled.  The profiles between the two versions of astropy are *very* different.

**Comment by karllark** [comment]
Fixed with upstream PR: https://github.com/astropy/astropy/pull/11365
