### ISSUE TITLE
DOC: Comparison of IDL versus python fitting results

### ISSUE THREAD

**Issue by karllark** [PAHFIT/pahfit#77]
Need a section in the documentation showing the differences between the IDL and python (v2.0) fit results for the same input spectrum.   Plots of the fitted spectra, components, etc. for single spectra and large samples of spectra would be good.

Given PAHFIT is doing non-linear fitting, it would be surprising if the results between the two versions were identical - even using the same fitter (aka optimizer) algorithm.

**Comment by karllark** [comment]
Useful plots and info in issue #77.

**Comment by els1** [comment]
This is completed. (Pull request #139 and #144).

**Comment by els1** [comment]
@alexmaragko What was the result for your comparison?

**Comment by karllark** [comment]
If this this has been completed, please close this issue.

**Comment by alexmaragko** [comment]
(Several months ago) I made a comparison of the peak intensities of the individual PAH features between IDL and Python in various galaxies. Variation around the ratio value of 1 was present, but I recall @karllark mentioning, when looking at the plots in one of our meetings, that it was acceptable.

**Comment by karllark** [comment]
Closing this issue all sounds good.  Please re-open if this is not the case.
