### ISSUE TITLE
Pure PAH spectrum module

### ISSUE THREAD

**Issue by alexmaragko** [PAHFIT/pahfit#78]
For people interested in using the NASA Ames PAH IR Spectroscopic Database Suite of tools, the pure PAH spectrum is required, currently not delivered in PAHFIT. I made a module that can be offered as separate script in the current scripts directory of PAHFIT. It requires two arguments, the user's input spectrum and PAHFIT's output file, to generate the total PAH spectrum from all the separate PAH components used in the fit. Optionally it will create a plot showing the separate components and the total PAH spectrum as in the example below. For people using both PAHFIT and PAHdb I feel this is something useful.  Let me know what you think and if I should proceed to a PR.
![ngc5194_fitpahspec](https://user-images.githubusercontent.com/33009979/104233517-af505780-545a-11eb-8300-2f7d4595ffee.png)

**Comment by jdtsmith** [comment]
PAHFIT_COMPONENTS was the IDL PAHFIT version of this.  It lets you take a given model fit and optionally pull out any of the components you want: lines, dust, dust features, starlight, etc.  That functional would be a super-set of this I think (unless I'm not understanding the connection the Ames database correctly).
