### ISSUE TITLE
Setup fitter to be have similar parameters values to IDL version

### ISSUE THREAD

**Issue by karllark** [PAHFIT/pahfit#84]
The parameters for the fitter need to be setup to be similar to the IDL version.  Specifically maximum number of interations, convergence criteria, etc.  This is to take advantage of the extensive testing the IDL version has undergone and to provide a fair comparison between the versions.

Will impact #74.

**Comment by ThomasSYLai** [comment]
Here are the comparisons of the different versions of PAHFIT (Python & IDL) using the M101 nucleus spectrum. Both fitters were fed with similar initial parameters and the maximum iteration is set to 400. 

(1) The following figure shows the ratio of PAH band powers measured by Python and IDL. Most of them are well below 5%. 
![dust_comparison](https://user-images.githubusercontent.com/13136763/104486930-715a4d00-559a-11eb-8f94-05ffe71778cb.png)

(2) The following figure shows the ratio of line powers measured by Python and IDL. The most obvious differences are [OIV] (25.87 um) and [FeII] (26.04 um). The reason for this is both features are close together and the two fitters treated different lines as the major component in the fitting process. If measuring the combined power of both features, the difference is < 5%.  
![line_comparison](https://user-images.githubusercontent.com/13136763/104486966-7ddea580-559a-11eb-8b8b-8b7f56b4f834.png)

The run-time (on my computer) for both fitters is listed for reference, which may also be relevant to #74.

IDL -> 50.55 sec -> iter=288
Python -> 104.59 sec -> iter=400(?)

Based on the warning of python PAHFIT, the fitter reaches maxiter = 400. Not sure how credible this warning is. 

This is the first attempt to test the differences between the two versions of PAHFIT. More extensive tests are still needed. But at least this result can give us some ideas on how different they are.

**Comment by karllark** [comment]
Awesome.  Great that the two versions are getting similar feature strengths.

The times are not as different as we were discussing on Monday.  Good to hear.  Almost looks like most of the timing difference is in the number of iterations the fitter uses.  Wonder if there is a different value for the convergence criteria between the two or something like that.

**Comment by karllark** [comment]
Or if the difference is that the IDL version updates the initial guesses based on the data and the python version does not.  See #82.

**Comment by alexmaragko** [comment]
Nice work @ThomasSYLai . I was wondering if you are comparing the flux of the features or the amplitude given in the output. I'm asking because I know there is a script in PAHFIT IDL to get the flux of the features, but there is not one yet for the Python version.

**Comment by ThomasSYLai** [comment]
@alexmaragko They are band strengths (flux). And yes, they are not provided in the Python version right now (will raise an issue right after). I calculated their strengths using equation (3) in Smith et al. (2007). And note that in this equation, fractional FWHM is used, while in Python we have FWHM.

**Comment by ThomasSYLai** [comment]
@karllark Based on my experience, the parameters and constraints set in the scipack file do make noticeable differences in the time and the fitted results. For example, the left panel shows the fitted result using scipack - scipack_ExGal_SpitzerIRSSLLL.ipac, while the right uses scipack with initial parameters similar to IDL PAHFIT. Both were set maxiter = 400. The left one did not have a good fit for features at PAH6.2, [NeII] (12.8 um), and [SIII] (18.7 um). Perhaps it can reach a better fit as maxiter increases, but this shows the scipack should be well trained to acquire reasonable results efficiently. And for sure, the initial guessing values are important as well. 

![image](https://user-images.githubusercontent.com/13136763/104496625-36124b00-55a7-11eb-8342-9df7153a8d11.png)

**Comment by karllark** [comment]
Good point.
