### ISSUE TITLE
Add module to calculate strengths of each band and PAH complex

### ISSUE THREAD

**Issue by ThomasSYLai** [PAHFIT/pahfit#86]
While the output in *.ipac file provides central wavelength, amp, and fwhm for each fitted feature, a module that is able to derive the strength of each band is needed. We may also need another module to take the measured strengths and combine them into PAH band complexes (e.g. PAH7.7, PAH11.3, and PAH17), which is an analogy to pahfit_main_feature_power in the IDL version.

**Comment by karllark** [comment]
Is this related to #19?  Or similar?  Or the same?

**Comment by ThomasSYLai** [comment]
Sorry. Didn't aware that it already exists. What I said is the same as #19.

**Comment by karllark** [comment]
No worries.  Thanks for opening this issue and I look forward to someone (you?) adding this important capability.
