### ISSUE TITLE
User Documentation 

### ISSUE THREAD

**Issue by BethanyRS** [PAHFIT/pahfit#90]
### Using Anaconda Prompt (anaconda3) on a Windows Computer:

* Before typing in any of the example code (such as "plot_pahfit --help"), you need to type something else first.  "python" works (ex. "python plot_pahfit --help").  I'm not sure if a shorter addition would also work.

* After running the run_pahfit example code, you get the following warning as an output
     * WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
Number of calls to function has reached maxfev = 1000.
     * Issue #89  also makes note of this problem.

 ### A typo?

* Under "Plotting" in "Plotting fit results" it reads, "To save the plot instead, use the “–savefig” command line option."  I think may want " --savefig".

**Comment by BethanyRS** [comment]
Note: it's at https://pahfit.readthedocs.io/en/latest/plot_result.html#plotting that I see the possible typo.  I think that it's fine at https://github.com/BethanyRS/pahfit/blob/master/docs/plot_result.rst

**Comment by karllark** [comment]
PR #107 fixes the need for `python` before the command.
The reaching maxfex=1000 is tracked in #89.
Will fix the typo (really a formatting issue) in a new PR.
