### ISSUE TITLE
Overlapping of words in documentation

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#91]
At the main page of the documentation, there are 2 lines where words overlap. See fig. 
![Screen Shot 2021-01-25 at 4 11 21 PM](https://user-images.githubusercontent.com/19981724/105766609-f8f37480-5f27-11eb-902f-0089fa49a2d9.png)

**Comment by karllark** [comment]
I don't see this on my browser (chrome).  What browser are you using?

![Screenshot from 2021-01-27 14-33-42](https://user-images.githubusercontent.com/1554536/106043658-bdce7e00-60ac-11eb-800a-f33002dd6f74.png)

**Comment by els1** [comment]
Safari.

**Comment by els1** [comment]
Also in the documentation on PAHFITBASE (on Safari):  https://pahfit.readthedocs.io/en/latest/api/pahfit.base.PAHFITBase.html 
![Screen Shot 2021-05-26 at 4 47 58 PM](https://user-images.githubusercontent.com/19981724/119729012-21da3680-be42-11eb-9b35-5fcc61900fad.png)

**Comment by karllark** [comment]
I don't see this with chrome on my laptop.  Have you tried looking at this with a different browser?  If you are the only one seeing this, it sounds like an issue with your computer/browser settings and not the pahfit docs.

**Comment by els1** [comment]
I don't have it using Chrome. It's specific to Safari. Perhaps someone else with a mac + Safari can check.

**Comment by ThomasSYLai** [comment]
@els1 It works fine on my mac with Safari v9.1.3.

**Comment by els1** [comment]
Interesting, I use Safari v14.0 on MacOS Catalina.

**Comment by karllark** [comment]
This sounds like only an issue with your computer @els1.  Not sure how to solve this issue and propose we close it as I feel it is not something we can solve in pahfit.
