### ISSUE TITLE
Guess function has to be optional

### ISSUE THREAD

**Issue by alexmaragko** [PAHFIT/pahfit#99]
When reading back the pahfit output file, e.g. when you want to recreate the plot using the plot_pahfit script, the code will call the guess function again and consequently it will lose the final output values, resulting in the wrong plot.

The same would happen if you'd simply want to read the output file back.

Therefore the guess function must become optional, perhaps as an argument when running pahfit to fit a spectrum.

**Comment by alexmaragko** [comment]
I made a PR #100 adding a "noguess" flag, so that the guess function will be used by default unless the "noguess" flag is given. The flag is set True by default in plot_pahfit.

**Comment by karllark** [comment]
Done in PR #101.
